### PR TITLE
Fixes Telescope issue #667, Added Cors Delegator Middleware

### PR DESCRIPTION
**Pull request by Metropass**
Closes https://github.com/Seneca-CDOT/telescope/issues/667

After many trials and tribulations, here's the CORS Delegator that fixes #667 in Telescope

This is a middleware function that will be passed when we configure CORS in Telescope. This is done asynchronously so that we won't have any init issues while the Telescope services start up.

### Layout
 `function corsDelegate(req, callback, options)`
 `req` - The Request Header that will be sent when CORS is being configured
`callback` - the callback function that `corsDelegate` will use when passed as an argument
`options` -  a JSON Object that will contain the different types of headers that we would like to be included when CORS is configured.

#### `origin` - Configures the `Access-Control-Allow-Origin` CORS Header. 

**Accepted Values:**
 `bool` - You can set `origin` to `true` to enable the requested Origin in the CORS Response.  Setting this to `false` will disable CORS.
 
 `string` - You cat set `origin` to a specific origin of your choice. Eg, setting `origin` to `www.telescope.cdot.systems` will only accept request from that address.
 
 `RegEx` - You can set `origin` to a Reg Ex pattern, and that will be used to test any address passed into CORS. Eg, the pattern `/telescope\.com$` will only accept addresses ending in `telescope.com`
 
 `Array` - If you wish to use any of the above value types, you may store them onto an array, and pass that instead. Eg, `['telescope.com', '/pattern\.com$']`

#### `method` - Configures the `Access-Control-Allow-Methods` CORS Header.
Accepted Values:
`string` - Accepts a string that's comma-delimited. Eg, `'GET,DELETE,POST'`
`array` - Accepts an array of strings. Eg, `['GET', 'DELETE', 'POST']`

#### `allowedHeaders` - Configures the `Access-Control-Allow-Headers` CORS Header.
Accepted Values:
`string` - Accepts a string that's comma-delimited. Eg, `'Content-Type,Authorization'`
`array` - Accepts an array of strings. Eg,  `['Content-Type','Authorization']`

#### `exposedHeaders` - Configures the `Access-Control-Expose-Headers` CORS Header.
Accepted Values:
`string` - Accepts a string that's comma-delimited. Eg, `'Content-Encoding,X-Kuma-Revision'`
`array` - Accepts an array of strings. Eg,  `['Content-Encoding', 'X-Kuma-Revision']`

#### `credentials` - Configures the `Access-Control-Allow-Credentials` CORS Header.
Accepted Value:
`bool` -  Set this to true to pass this header, otherwise it won't be included

#### `maxAge` - Configures the `Access-Control-Max-Age` CORS Header.
Accepted Value:
`int` - an integer that's above the value of 0, otherwise it won't be included.

### Example of the CORS Delegator Use Case

`app.use(cors(corsDelegate({exposedHeaders: ['X-Total-Count', 'Link'], credentials: true})), function (req, res, next){
res.json({msg: 'CORS is now Enabled for the Backend'});

});`

### CODE REVIEW

**Review by humphd — COMMENTED** [review]
I'm reading this code, but without tests or docs in the README, I'm have a bit of trouble understanding how you plan on using it.  Can you give a brief example of how it would be used, and how it differs from the `cors()` middleware we already have?  See https://www.npmjs.com/package/cors#configuration-options

**Comment by Metropass** [comment]
> I'm reading this code, but without tests or docs in the README, I'm have a bit of trouble understanding how you plan on using it. Can you give a brief example of how it would be used, and how it differs from the `cors()` middleware we already have? See https://www.npmjs.com/package/cors#configuration-options

I wanted to write it this way, so that if at anytime something goes wrong with CORS pre-flights/any issues, we could just check whether or not the delegator successfully created a CORS Session (and if it doesn't we could pass it in the logger as an error)

**Comment by humphd** [comment]
@Metropass You say "you wanted to write it this way," and that's what I'm trying to understand a bit better.  Can you give an example of how it would be used in Telescope?

**Comment by humphd** [comment]
@Metropass and I discussed this yesterday, and I think we're going to try this in a different way.  Closing this one for now.

**Pull request closed without merging**
