### PR TITLE
Added Prettier for Satellite

### PR DESCRIPTION
**Pull request by Metropass**
Similar to what we use in Telescope, this is just an easy port of Prettier for Satellite for future use

### CODE REVIEW

**Comment by Metropass** [comment]
I need to clean up the commits, they're quite scattered and shouldn't be there. I'll invoke `cherry-pick`, if that's possible.

**Comment by humphd** [comment]
Let me know when you've cleaned up this git history to a single commit off master, and I'll review it then.

**Comment by humphd** [comment]
@Metropass there's something wrong with your git workflow, and I'd like you to sort it out:

Screen Shot 2021-03-16 at 2 05 07 PM

You are constantly creating branches off of old work, then merging master.  This kind of thing is OK when students are starting in DPS909, but at this point, I'd love to have your PRs just include the appropriate work, and be based off of latest master.

Please read https://github.com/Seneca-CDOT/telescope/blob/master/docs/git-workflow.md and make sure you are doing your PRs correctly.

**Review by humphd — CHANGES_REQUESTED** [review]
I'll review this once it has been cleaned of other commits/branches.  Let me know.

**Review by humphd — APPROVED** [review]

**Comment by humphd** [comment]
One thing this is going to do is cause some extra stuff to appear in people's PRs until we get all the files re-formatted with these new prettier values.

**Pull request merged**
